services:
  database:
    image: mariadb:10.8.3
    # Uncomment below when on Mac M1
    platform: linux/arm64/v8
    command: "--default-authentication-plugin=mysql_native_password  --max_allowed_packet=10000M --sql_mode=NO_ENGINE_SUBSTITUTION"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 8080:80
    depends_on:
      - database